//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int Id { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> CoffeeId { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> temporderid { get; set; }
        public Nullable<int> orderid { get; set; }
    
        public virtual coffees coffees { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
    }
}
