//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class coffees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coffees()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
            this.Basket = new HashSet<Basket>();
        }
    
        public int Id { get; set; }
        public string CoffeeName { get; set; }
        public Nullable<int> CoffeePrice { get; set; }
        public string CoffeeImagePath { get; set; }
        public string CoffeeDescription { get; set; }
        public Nullable<bool> CoffeeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
    }
}
